{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "gatekeeper-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gatekeeper-operator.labels" . | nindent 4 }}
    gatekeeper.sh/system: "yes"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "gatekeeper-operator.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "gatekeeper-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end -}}
