apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gatekeeper-operator.fullname" . }}-webhook-server-cert
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gatekeeper-operator.labels" . | nindent 4 }}
    gatekeeper.sh/system: "yes"
