apiVersion: constraints.gatekeeper.sh/v1beta1
kind: AllowedUsersConstraint
metadata:
  name: default-ns-pods-allowed-user-ranges
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
        namespace: ["default"]
  parameters:
    runAsUser:
      rule: MustRunAs
      ranges:
        - min: 100
          max: 200
