apiVersion: v1
kind: Pod
metadata:
  name: nginx-users
  labels:
    app: nginx-users
spec:
  containers:
    - name: nginx
      image: nginx
      securityContext:
        runAsUser: 250
        runAsGroup: 250
        supplementalGroups: 250
        fsGroup: 250
