apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: requiredannotations
spec:
  crd:
    spec:
      names:
        kind: RequiredAnnotations
        listKind: RequiredAnnotationsList
        plural: requiredannotations
        singular: requiredannotations
      validation:
        # Schema for the `parameters` field in the constraint
        openAPIV3Schema:
          properties:
            annotations:
              type: array
              items:
                type: object
                properties:
                  key:
                    type: string
                  desiredValue:
                    type: string
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package requiredannotations

        violation[{"msg": msg, "details": {}}] {
          provided := {annotation | input.review.object.metadata.annotations[annotation]}
          required := {annotation | annotation := input.parameters.annotations[_].key}
          missing := required - provided
          count(missing) > 0          
          msg := sprintf("you must provide annotations: '%v'.", [missing])
        }

        violation[{"msg": msg, "details": {}}] {
          value := input.review.object.metadata.annotations[key]
          expected := input.parameters.annotations[_]
          expected.key == key
          expected.desiredValue != value
          def_msg := sprintf("Annotation <%v: %v> does not equal allowed value: %v", [key, value, expected.desiredValue])
        }
