apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8suniqueingresshost
spec:
  crd:
    spec:
      names:
        kind: K8sUniqueIngressHost
        listKind: K8sUniqueIngressHostList
        plural: k8suniqueingresshost
        singular: k8suniqueingresshost
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8suniqueingresshost
       
        violation[{"msg": msg}] {
          input.review.kind.kind == "Ingress"              
          host := input.review.object.spec.rules[_].host
          ingresses := data.inventory.namespace[_][_]["Ingress"]
          ingresses[_].spec.rules[_].host == host
          msg := sprintf("ingress host conflicts with an existing ingress <%v>", [host])
        }
