# permissions for end users to view assigns.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: assign-viewer-role
rules:
- apiGroups:
  - mutations.gatekeeper.sh
  resources:
  - assigns
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mutations.gatekeeper.sh
  resources:
  - assigns/status
  verbs:
  - get
