apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8spspapparmor
spec:
  crd:
    spec:
      names:
        kind: K8sPSPAppArmor
        listKind: K8sPSPAppArmorList
        plural: k8spspapparmor
        singular: k8spspapparmor
      validation:
        # Schema for the `parameters` field
        openAPIV3Schema:
          properties:
            allowedProfiles:
              type: array
              items:
                type: string
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8spspapparmor

        violation[{"msg": msg, "details": {}}] {
            metadata := input.review.object.metadata
            not input_apparmor_allowed(metadata)
            msg := sprintf("apparmor profile is not allowed, pod: %v. Allowed profiles: %v", [input.review.object.metadata.name, input.parameters.allowedProfiles])
        }

        input_apparmor_allowed(metadata) {
            metadata.annotations
            not metadata.annotations["apparmor.security.beta.kubernetes.io/pod"]
        }

        input_apparmor_allowed(metadata) {
            metadata.annotations["apparmor.security.beta.kubernetes.io/pod"] == input.parameters.allowedProfiles[i]
        }
