# You can copy this file to manager_image_patch.yaml to specify a prebuilt image
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: controller-manager
  namespace: system
spec:
  template:
    spec:
      containers:
      # Change the value of image field below to your controller image URL
      - image: <IMAGE URL>
        name: manager
