replicas: 3
auditInterval: 60
constraintViolationsLimit: 20
auditFromCache: false
createNamespace: true
disableValidatingWebhook: false
auditChunkSize: 0
logLevel: INFO
emitAdmissionEvents: false
emitAuditEvents: false
image:
  repository: openpolicyagent/gatekeeper
  release: v3.3.0-beta.2
  pullPolicy: IfNotPresent
  pullSecrets: []
nodeSelector: { kubernetes.io/os: linux }
affinity: 
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: gatekeeper.sh/operation
            operator: In
            values:
            - webhook
        topologyKey: kubernetes.io/hostname
      weight: 100
tolerations: []
podAnnotations:
  { container.seccomp.security.alpha.kubernetes.io/manager: runtime/default }
secretAnnotations: {}
controllerManager:
  priorityClassName: system-cluster-critical
  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
audit:
  priorityClassName: system-cluster-critical
  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
customResourceDefinitions:
  create: true
