name: mutation
on:
  pull_request:
    types: [ labeled ]

env:
  GITHUB_REPO: open-policy-agent/gatekeeper
  IMAGE_REPO: openpolicyagent/gatekeeper

jobs:
  build_mutation_test:
    if: ${{ github.event.label.name == 'mutation' }}
    name: "Build and Test Mutation"
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Bootstrap e2e
        run: |
          mkdir -p $GITHUB_WORKSPACE/bin
          echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH
          make e2e-bootstrap

      - name: Run e2e mutation
        run: |
          make e2e-build-load-image IMG=gatekeeper-e2e:latest
          make deploy-mutation IMG=gatekeeper-e2e:latest USE_LOCAL_IMG=true
          make test-e2e ENABLE_MUTATION_TESTS=1

      - name: Save logs
        run: |
          kubectl logs -n gatekeeper-system -l control-plane=controller-manager --tail=-1 > logs-controller-mutation.json
          kubectl logs -n gatekeeper-system -l control-plane=audit-controller --tail=-1 > logs-audit-mutation.json

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: logs
          path: |
            logs-*.json
